services:
  postgres:
    image: postgres:15
    container_name: pocket_ledger_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: pocket_ledger_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - ./wait-for-postgres.sh:/app/wait-for-postgres.sh
    command: sh -c "chmod +x ./wait-for-postgres.sh && ./wait-for-postgres.sh node server.js"
    restart: unless-stopped

volumes:
  postgres_data:
